Add support for addminingaddr, delminingaddr, and setminingaddrs
btcsuite/btcrpcclient pull request #105
Opened 2016-11-30 02:07 UTC by Roasbeef

This commit adds support for the three new RPC's which were added in btcsuite/btcd#845.

2016-11-30 16:41 UTC, davecgh requested changes

2016-11-30 16:41 UTC, davecgh commented on extensions.go
> +// FutureSetGenerateResult is a future promise to deliver the result of a
s/FutureSetGenerateResult /FutureAddMiningAddrResult/

2016-11-30 16:41 UTC, davecgh commented on extensions.go
> +type FutureDelMiningAddrsResult chan *response
Along the same lines as the related PRs, would you mind defining all of these delete mining result funcs before the list addresses ones so they're consistently defined in the same order (alphabetical) as btcd/btcutil/btcrpcclient.

2016-11-30 16:41 UTC, davecgh commented on extensions.go
> +// Receive waits for the response promised by the future and returns true if
Looks like this was copied but not updated.

2016-11-30 23:59 UTC, Roasbeef commented on extensions.go
> +// Receive waits for the response promised by the future and returns true if
Fixed.

2016-11-30 23:59 UTC, Roasbeef commented on extensions.go
> +type FutureDelMiningAddrsResult chan *response
Fixed.

2016-11-30 23:59 UTC, Roasbeef commented on extensions.go
> +// FutureSetGenerateResult is a future promise to deliver the result of a
Fixed.

2017-06-06 03:24 UTC, davecgh approved these changes
OK once btcsuite/btcd#845 is also merged.

2017-08-16 17:42 UTC, davecgh commented
The rpcclient is now part of the main btcd repository.  Going to close this.  Please reopen it there.

2017-08-16 17:42 UTC, closed without merging